services:
  - type: web
    name: quarkus-addition-calculator
    env: java
    branch: main
    buildCommand: ./mvnw clean package -Pnative=false
    startCommand: java -jar target/*-runner.jar
    envVars:
      - key: JAVA_OPTS
        value: -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT}