
#Approach 1:
#services:
#  - type: web
#    name: addition-calculator
#    runtime: java17
#    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
#    startCommand: java -jar target/*-runner.jar
#    envVars:
#      - key: JAVA_OPTS
#        value: -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT}

#Approach 2:
#services:
#  - type: web
#    name: addition-calculator
#    runtime: java17
#    buildCommand: export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) && chmod +x mvnw && ./mvnw clean package -DskipTests
#    startCommand: java -jar target/*-runner.jar
#    envVars:
#      - key: JAVA_OPTS
#        value: -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT}

#Approach 3:
#services:
#  - type: web
#    name: addition-calculator
#    runtime: java17
#    buildCommand: |
#      export JAVA_HOME=/opt/java/openjdk
#      chmod +x mvnw
#      ./mvnw clean package -DskipTests
#    startCommand: java -jar target/*-runner.jar
#    envVars:
#      - key: JAVA_OPTS
#        value: -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT}

#Approach 3 modified:
#services:
#  - type: web
#    name: addition-calculator
#    runtime: java17
#    buildCommand: export JAVA_HOME=/opt/java/openjdk && chmod +x mvnw && ./mvnw clean package -DskipTests
#    startCommand: java -jar target/*-runner.jar
#    envVars:
#      - key: JAVA_OPTS
#        value: -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT}

#Approach 4
#services:
#  - type: web
#    name: addition-calculator
#    runtime: java17
#    buildCommand: mvn clean package -DskipTests
#    startCommand: java -jar target/*-runner.jar
#    envVars:
#      - key: JAVA_OPTS
#        value: -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT}

#Approach 5:
#services:
#  - type: web
#    name: addition-calculator
#    runtime: ubuntu
#    buildCommand: |
#      apt-get update
#      apt-get install -y openjdk-17-jdk
#      chmod +x mvnw
#      ./mvnw clean package -DskipTests
#    startCommand: java -jar target/*-runner.jar
#    envVars:
#      - key: PORT
#        value: 7453
#      - key: QUARKUS_HTTP_HOST
#        value: 0.0.0.0

#Approach 6 - with Dockerfile:
#services:
#  - type: web
#    name: addition-calculator
#    runtime: docker
#    dockerfilePath: ./Dockerfile
#    envVars:
#      - key: PORT
#        value: 7453
#      - key: QUARKUS_HTTP_HOST
#        value: 0.0.0.0

#Approach 7
#services:
#  - type: web
#    name: addition-calculator
#    runtime: docker
#    dockerfilePath: ./Dockerfile

#Approach 8
services:
  - type: web
    name: addition-calculator
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 7453