services:
  - type: web
    name: quarkus-calculator
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*-runner.jar
    envVars:
      - key: JAVA_OPTS
        value: -Dquarkus.http.host=0.0.0.0
      - key: PORT
        value: 7453